import re


a = "waaaaaaaaaaaaaaaQaaaaaaaaaaaawwwQaaaaaaaaaQaaaaaaaaQaaaaaaQaaaaawQaaawQaaQaQddQdaQdddQddddQdddQddddQdddddddQdddddQddddddddQdddddddddQddddddddddQdddddddddddQddddddddddddddddQdddddddddddddQdddddddddddddddwwQddddddddddddddwwwQdddddddddddddQddddddddddddQddddddddddddQdddddddddddQddddddddddQdddddddddddQddddddddQddddddddddwwQdddddddddddddwQddddddQdddddQdddddQdddddQddddQdddwwwQddQdQdaQawwwQaaaaQaaawQwwwaaaaaQaaaaaaaQaaaaaaaaQaaaaaaaaawQaaaaaaaaaaQaaaaaaaaaaaQaaaaaaaaaaaaaawQaaaaaaaaaaaaaaaQaaaaaaaaaaaaaQaaaaaaaaaaaaaaQaaaaaaaaaaaaQaaaaaaaaaaaaawQaaaaaaaaaaaaaaaaQwaaaaaaaaaaaaaaaaQwaaaaaaaaaaaaQaaaaaaaaaawwwQaaaaaaaaaaaaaaaaQaaaaaaaaaaaaaaaaQaaaaaaaaaaaaaaaQaaaaaaaaaaaaaaaQaaaaaaaaaaaaaaaQaaaaaaaaaaaaaQaaaaaaaaaaaaQwwwaaaaaaQwaaaaaQwaaaaQaaQaQaaQaQQdQddQQdQddQwwwdddddQdddddddQwdddddddddQwdddddddddddddQwwwddddddddddddddQddddddddddddddddQddddddddddddddddQwddddQwdddddddQddddddddQwwwdddddddddQddddddddddQwdddddddddQdddddddddddddQddddddddddddddQdddddddddddddddQwdddddddddddddddQwwddddddddddddddQddddddddddddQddddddddddddddddQdddddddddddddddQQdddddQddddQdddQddQdQaaQwaaaaaaaQaaaaQaaaaaQaaaaaaQaaaaaaaQaaaaQQaQaaQaQwwQdddddddddddddQwddddddddddddQddddddddddQwdddddddddddQddddddddddddddddQddddddddddddddddQddddddddQdddddddddQdddddddQdddddQddddddQddddddQddddddddddddddQddddddddddddQdddddddddQdddddddddQddddddddddQddQddQaaaaaaaaaaaaaaQaaaaaaaaaaaaQwaaaaaaaaaQwwaaaaaQaaaaQaaaaaaaQaaaaaaaQaaaaaaQaaaaaaQwwwaaaaaaaaaaQaaaaaaaaaaQdddddddQdddddQwdddQddddQdddQwwwQddQdddQddddQwwdQwddddQwwddddddQwdddddddQdddddQdddddQddddddddQdddddddddQdddddddQdddddddddQddddddddQddddddddddQddddddddddQdddddddddddddQddddddddddddddQwddddddddddddddddQddddddddddddQdddddddddddddddQddddddddddddddddQdddddddddddddQdddddddddddddQddddddddddddddQdddddddddddddddQddddddddddddddddQddddddddddddddddQddddddddddddddQwdddddddddddQddddddddQddddddddddQdddddddddQddddddddddQdddddddddddQddddddddddddQwwwdddddddddddddQddddddddddddddddQddddddddddddddddQddddddddddddddQwdddddddddddddQdddddddddddQwdddddddQwddddddddQwwddddddQdddddQdddddddddddQdddddddddddddQwwddddddddQwwwdddddddddddddddQddddddddddddQddddddddddddQdddddddddddddQddddddddddddddQddddddddddQddddddddQdddddddQddQdddQddddQQdQdQdQddQdddQddddQwwwddQwddddddQddddQdddddQddddddQddddddddQwddddQwddddddQwwddddddddddQdddddddQdddddddddQdddddddddddQddddddddddddQdddddddddddddQddddddddddddddQdddddddddddddQddddddddQddddddddQddddddddQdddddQdddddddQddddddddddQddddddddddQdddddddddddQddddddddddddQwwddddddQdddddddddQddQdQdQwddddddddddddddddQdddddddddddddddQwddddddddddddddQwwwdddddddddQwwddddddddddddQddddddddddQdddddddQdddddQwwwddddddddQwwddddddQwwddddddddQddddddddQddddddQddddddQddddddQdddddddQddddQwddQddQdddQdddddQdQddQwddddddddddddQwwwaaaQaQaaaaQaaaQaaQaaQaQaaaaaaQwaaaaaQaaaaaaaQaQQaQQaaQaaQaaQaaQwwaQaaQaQdQdQdQdQddddddddddQdddQdddQwwwddQwdddQwwddQwwddddddQddddddddQwdddddddddQwddddddQwwdddQdddddQdddddQdddddddddQdddddddQdddddddQwwwdQdddddQdddQQaQaaQaaQaaQaQQwaaaaQaaaaQaaaQaaaaQaaaaQaaaaQwaaaQwaaaaQaaaaQaaaaQwwaaaQaQQaaQaQaQaQaaaQaaaaQaaaaQwaaaaQaaQwQdQQdQddQddQwwwaaaaaQwwaaQaaaaQaaaaQaaQaaaQaQaaaaaQaaaaQaaaaa"

x = a.upper()


def compress_string(s):
    result = []
    for match in re.finditer(r'(.)\1*', s):
        char = match.group(1)
        count = len(match.group(0))
        if count > 1:
            result.append(f'[{char}]*{count}')
        else:
            result.append(f'[{char}]')
    return ' + '.join(result)

print(compress_string(x))
